name: Subgraph CI

on: [workflow_dispatch, pull_request, push]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - name: Generate code
        run: |
          cd token-buyer-subgraph
          yarn codegen
      - name: Run tests
        run: |
          cd token-buyer-subgraph
          yarn test
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
